# Generated by Django 4.2.7 on 2023-11-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('floor', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('cancel', 'Отмена'), ('purchase', 'Куплено'), ('reserve', 'Бронь'), ('barter', 'Бартер'), ('installment', 'Рассроч'), ('active', 'Активный')], max_length=25)),
                ('kv', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.object')),
            ],
        ),
    ]
